spring:
  datasource:
    url: jdbc:mysql://localhost/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: mysql
  jpa:
    hibernate:
      # 会自动比对数据中的字段和实体类的映射,如果不一致的的,会把实体类的更改映射到数据库中
      # 线上环境的话,会更改成none,就算实体类更改也不会映射到数据库
      ddl-auto: update
    # 把sql语句显示在控制台
    show-sql: true
# 配置日志的级别
logging:
  level:
    root: info
    com.blog: debug
  file: log/blog-dev.log